# Generated by Django 5.0.2 on 2024-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
